In [27]:
import numpy as np

In [3]:
arr = np.array([[1,2,3] , [3,2,1] , [4,5,6]])
arr

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.shape

(3, 3)

In [8]:
arr_zero = np.zeros((2,5))
arr_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
arr_zero.dtype

dtype('float64')

In [12]:
rng = np.arange(15)
rng

array([1, 2, 3, 4])

In [16]:
lspace = np.linspace(1,9,10)
lspace

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [18]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.11387449e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 6.89804133e-307,
        1.11261162e-306, 8.34443015e-308, 8.34402698e-308]])

In [20]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
x = [[1,2,3] , [4,5,6] , [7,8,9]]
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar.sum(axis=0)

array([12, 15, 18])

In [34]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
ar.flat

In [37]:
ar.ndim

2

In [38]:
ar.size

9

In [41]:
ar.nbytes

72

In [42]:
one = np.array([1,3,454,3,544])
one.argmax()

np.int64(4)

In [43]:
one.argmin()

np.int64(0)

In [44]:
one.argsort()

array([0, 1, 3, 2, 4])