In [1]:
import numpy as np

# NUMPY 

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [10]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
type(arr2)

numpy.ndarray

In [14]:
ar3 = np.zeros((10,10))
ar3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
ar4 = np.full((5,5),10)             
ar4

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [17]:
ar5 = np.arange(10,20)              #range array
ar5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
ar6 = np.arange(0,100,5)                          #range with gape
ar6

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [24]:
ar7 = np.random.randint(100,200,10)                         #random number range and given val
ar7

array([144, 145, 138, 129, 192, 193, 149, 155, 178, 193], dtype=int32)

In [25]:
ar8 = np.array([[1,2,3,4,5,6,7,8,9] , [9,8,7,6,5,4,3,2,1]])             #shape col and row
ar8.shape

(2, 9)

In [27]:
ar8.shape = (9,2)                      #Change the dimension
ar8

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 9],
       [8, 7],
       [6, 5],
       [4, 3],
       [2, 1]])

                     #JOINING NUMPY ARRAY

#Vstack

In [36]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [37]:
np.vstack((a1,a2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#Hstack horizontal stack

In [38]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

#Col stack

In [39]:
np.column_stack((a1,a2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#Intersection and diff

In [43]:
n1 = np.array([10,20,30,40,50])
n2 = np.array([20,50,80,60,30])

In [44]:
np.intersect1d(n1,n2)

array([20, 30, 50])

In [47]:
np.setdiff1d(n1,n2)

array([10, 40])

            # ARRAY MATHEMATICS

In [48]:
x1 = np.array([10,20])
x2 = np.array([30,40])

In [50]:
np.sum([x1,x2])

np.int64(100)

In [51]:
np.sum([x1,x2],axis=0)                       #  col val

array([40, 60])

In [53]:
np.sum([x1,x2],axis=1)                      #row val

array([30, 70])

           #MATH WITH SCALAR VAL

In [54]:
z1 = np.array([1,2,3,4,5,6])          #ADDTION
z1 = z1+1
z1

array([2, 3, 4, 5, 6, 7])

In [57]:
z1 = z1*1                        #MULTIPLICATIONS
z1

array([1, 2, 3, 4, 5, 6])

In [58]:
z1 = z1-1                        #MULTIPLICATIONS
z1

array([0, 1, 2, 3, 4, 5])

In [59]:
z1 = z1/1                        #MULTIPLICATIONS
z1

array([0., 1., 2., 3., 4., 5.])

                                       #STATISTICAL MATH FUN

In [64]:
d = np.random.randint(1,50,10)
d

array([45, 17, 39, 27, 44, 39, 45, 10, 27, 44], dtype=int32)

In [68]:
np.mean(d)

np.float64(33.7)

In [66]:
np.std(d)

np.float64(12.05860688471102)

In [69]:
np.median(d)

np.float64(39.0)

                                       #Save and load

In [73]:
k = np.array([1,2,3,4,5,6,6,7,8,9])
np.save("my_arr",k)

In [76]:
new = np.load("my_arr.npy")
new

array([1, 2, 3, 4, 5, 6, 6, 7, 8, 9])